apiVersion: v1
description: Elasticsearch stats exporter for Prometheus
name: prometheus-logstash-exporter
version: 0.1.0
kubeVersion: ">=1.10.0-0"
appVersion: 0.7.0
home: https://github.com/alxrem/prometheus-logstash-exporter
sources:
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-logstash-exporter
keywords:
  - metrics
  - logstash
  - monitoring
maintainers:
  - name: ebuildy
    email: ebuildy@gmail.com
